name: Dispatch to dependents
on:
  push:
    branches:
    - main
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        dependents: [RTTI, SIMD, Fractalloc, Anyness, Flow, Math, Entity]
    name: Trigger Langulus::${{matrix.dependents}}'s workflow
    runs-on: ubuntu-latest
    steps:
      - run: >
          curl
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${{secrets.TRIGGER_WORKFLOWS}}"
          https://api.github.com/repos/Langulus/${{matrix.dependents}}/dispatches
          -d '{"event_type":"[Logger] ${{github.event.head_commit.message}}","client_payload":{"cause":"Logger"}}'